### ISSUE TITLE
Training crash at epoch 15 at src.d_fine.arch.utils:generalized_box_iou:40

### ISSUE THREAD

**Issue by Wavelet303** [ArgoHA/custom_d_fine#4]
👋 Hi @ArgoHA ,

First of all, thank you for the great work! The API is really well designed and has made it very easy to train a SOA model on my own dataset. It's truly valuable to have such accessible and powerful tools available to the community — much appreciated! 🙌

I'm training a custom object detection model and ran into a critical error during epoch 15 that halts training completely. I'm sharing the details below in case it helps with debugging.

****🧾 Training Setup****

- Training images: 15,502
- Validation images: 2,191
- Background images: 9,283
- Batch size: 6
- Total epochs: 70
- GPU: NVIDIA RTX 3070 (12 GB)
- Mixed precision: Enabled
- Learning rate: Default (no custom LR specified)

📉 **Observed behavior**
Training works fine until epoch 15. However, during this epoch, I get the following error:

__CUDA error: an illegal memory access was encountered
src.d_fine.arch.utils:generalized_box_iou:40 - tensor([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]], device='cuda:0')_

✅ **Additional context**
The issue happened after successfully completing 14 epochs.

I'm using the pretrained weights from pretrained/dfine_x_coco.pth.

Logging is done with wandb in offline mode.

🔧 **Feature suggestions**

If possible, I’d also like to ask:

Will there be support for TensorBoard in the future? It would be great to have that option in addition to wandb.

Would it be possible to add a parameter to save model weights every N epochs? That would be really useful to prevent loss of progress if a crash like this happens later in training.

Let me know if there's any way I can help reproduce or debug this issue further. Thanks again for your amazing work on this project!

Best,

**Comment by ArgoHA** [comment]
Hey. NaNs you see means that gradients are blowing. To deal with it you can try:
- Lower learning rate
- Disable AMP
- maybe less background images, but I can't confirm this will help

I would start with this:
```
    x:
      backbone_lr: 0.0000015
      base_lr: 0.00015
```

I originally took lrs from authors and tuned n/s/m models. I didn't work a lot with l/x, so I don't have a ready number that will definitely work. If you can't afford another fail in training - turn off amp.

Let me know what results you will get.

About features:
- Tensorboard - I can add that at some point
- You can't lose model during training because every best model is resaved and also latest epoch's model is saved too. So you always have 2 weights (best, last)

**Comment by Wavelet303** [comment]
Hey, thanks a lot for the quick and helpful response!

I'll first follow your suggestion and lower the learning rate using:

x:
  backbone_lr: 0.0000015
  base_lr: 0.0001

I've also disabled AMP for now to avoid any instability due to mixed precision, as I really can’t afford another failed run at this stage.

Just for context, I'm working on a defect detection task with multiple defect classes, and a large number of background-only images are a natural part of the dataset — unfortunately, I can't reduce or filter them out, since they are important for improving precision and avoiding false positives.

Thanks again for confirming the model is always saved both as best and last — that’s very reassuring.

Looking forward to trying the new setup, and I’ll keep you posted on how it goes. Also, great to hear that TensorBoard support might be added in the future — would love that!

Best,

**Comment by ArgoHA** [comment]
Thanks for the context. Just some thoughts on what I would do in your scenario:
1. Collet a separate test set with a lot of background images, representing natural distribution
2. Train a model as you currently do
3. Train a model with 90-95% of images with objects and 10% negatives. For example 6 219 with objects and 500 negatives.
4. Compare both models on the realistic test set, check best thresholds for both models.

I worked with defect detection and with rare objects numerous times. I would not suggest having 50% of your training data as negatives, model can't train very well (other models too). Some models even spit a warning if in a batch you don't get a single object. Because model can't train without target objects.

If after everything you are not happy with the precision, you should think about using a second model as a validator (it can be big and slow, inferenced on a higher image size)

**Comment by Wavelet303** [comment]
Thanks for the advice — really appreciate it!

Just to add some context: I’ve previously trained the model successfully using Ultralytics (RT-DETR-X) with the same amount of background images, and achieved pretty solid results — 0.89 recall and 0.9 precision for detecting 13 different defect classes.

Interestingly, with a different camera setup and a different set of defects, I actually got better recall and precision when reducing background images to 50% and even down to 10%. So I didn’t find a consistent rule that clearly favors reducing background images in all cases.

That said, your explanation makes a lot of sense, and I’ll definitely follow your advice — I’ll prepare the realistic test set and run both training strategies as you described. Let’s see how they compare on a real-world distribution.

Thanks again for sharing your experience! I’ll keep you posted on how it goes.

Best,

**Comment by ArgoHA** [comment]
@Wavelet303 when you finish your experiments please let me know what ended up working. I will update documentation with new LRs if they worked in your case

**Comment by Wavelet303** [comment]
Hi @ArgoHA 👋,

Just wanted to update you — I’ve completed training the model X with the new learning rate settings you suggested (backbone_lr: 0.0000015, base_lr: 0.0001) and ran it for 40 epochs without any issues. Everything went smoothly, and no NaNs or memory-related errors occurred this time.

Interestingly, I got the best results at epoch 23, with a precision of 0.7761 and recall of 0.8003.

For reference, using the same dataset with Ultralytics and RT-DETR-X, I obtained slightly higher precision (0.80195) but lower recall (0.74341). From the various experiments I’ve conducted, it seems that D-Fine tends to achieve better recall at the cost of a slightly lower precision, which makes sense for my defect detection use case. Also worth noting: D-Fine converges more quickly in my experience.

For the next experiment, I’ll follow your suggestion and reduce the number of background-only images in the training set to see how it affects overall performance.

On the other hand, I also trained D-Fine-S on a different dataset (a different problem) using default learning rate settings, with:

- 4182 images
 
- No background-only images
 
- Image size: 512x512
 
- Batch size: 16

- AMP enabled

- 40 epochs planned

However, during epoch 14, I encountered the same NaNs error as previously reported.

Just out of curiosity — is this kind of NaN error also known to happen with the vanilla version of the library (not just D-Fine variants)? I’ve seen it occur there too, and since I’m evaluating the library for use in a production environment, I’d like to better understand how to prevent such issues in a robust way.

Also, I think I may have found a potential bug:
If the training spans multiple days, running the post-training evaluation commands:

_python -m src.dl.export         # Exports weights in various formats after training
python -m src.dl.bench          # Runs all exported models on the test set_

will raise an error because the script expects the export folder to be dated with the current day, not the day training actually finished. This can cause the script to fail when it can’t find the expected folder. Might be worth making the script look for the most recent completed run instead?

Thanks again for your support — I’ll keep you posted!

Best,

**Comment by ArgoHA** [comment]
Hey, thanks for sharing your results!

1) Different models can have different thresholds. Ideally you should pick the best threshold for each model, then compare metrics. For D-FINE threshold can easily be 0.05 higher and you will see same precision and higher recall (for example). By the way, at the end of training you can see in logs best threshold calculated during final validation.

2) I also see it converging quicker. But vanilla version is a lot slower because of their implementation of EMA.

3) In Vanilla version you will less likely get NaNs. They happen because of OneCyclerRL I use. The peak LR value sometimes is too high. It is good for faster convergence, but with some datasets can be unstable. To fix this, I recommend using lower LRs, as you did with X model. (check commented value in configs). I tested this model on ~10 datasets and only 1 of them was failing with default LRs, so I used lower ones. If you want to be safe, please use them. I will reconsider default LR after some benchmarking with several different datasets. But it might take some time.

4) Thanks for mentioning the dates issue. I also find it inconvenient, with longer sessions. I will push an update fixing it this week.

**Comment by ArgoHA** [comment]
@Wavelet303 
Dates issue has been resolved, please use the latest version of this repo.

**Comment by q-prashant** [comment]
I faced a similar issue with `l` variant where the training would crash during epoch 11 with not much info on the reason
```console
2025-05-13 21:22:58
Epoch 11/70:  24%|██▍       | 3051/12763 [21:18<1:07:22,  2.40batch/s, eta=94:01, loss=27.9, vram=85%]2025-05-14 03:14:16.820 | ERROR    | src.d_fine.arch.utils:generalized_box_iou:40 - tensor([[nan, nan, nan, nan],
 97
2025-05-13 21:44:16
        [nan, nan, nan, nan],
 98
2025-05-13 21:44:16
        [nan, nan, nan, nan],
 99
2025-05-13 21:44:16
        ...,
100
2025-05-13 21:44:16
        [nan, nan, nan, nan],
101
2025-05-13 21:44:16
        [nan, nan, nan, nan],
102
2025-05-13 21:44:16
        [nan, nan, nan, nan]], device='cuda:0')
103
2025-05-13 21:44:17
Epoch 11/70:  24%|██▍       | 3051/12763 [21:18<1:07:50,  2.39batch/s, eta=94:01, loss=27.9, vram=85%]
104
2025-05-13 21:44:17
2025-05-14 03:14:17.270 | ERROR    | __main__:main:458 -
105
2025-05-13 21:44:17
2025-05-14 03:14:17.276 | INFO     | __main__:main:460 - Evaluating best model...
106
2025-05-13 21:49:58
2025-05-14 03:19:58.960 | INFO     | src.dl.validator:save_plots:331 - Best Threshold: 0.55 with F1 Score: 0.871
107
2025-05-13 21:49:59
2025-05-14 03:19:59.053 | INFO     | src.dl.utils:log_metrics_locally:64 - Best epoch metrics:
108
2025-05-13 21:49:59
+-----+--------+--------+-----------+--------+-------+-----------+--------+--------+-------+
109
2025-05-13 21:49:59
|     | mAP_50 |   f1   | precision | recall |  iou  | mAP_50_95 |  TPs   |  FPs   |  FNs  |
110
2025-05-13 21:49:59
+-----+--------+--------+-----------+--------+-------+-----------+--------+--------+-------+
111
2025-05-13 21:49:59
| val | 0.9029 | 0.8687 |  0.8341   | 0.9063 | 0.627 |  0.5714   | 9033.0 | 1797.0 | 934.0 |
112
2025-05-13 21:49:59
+-----+--------+--------+-----------+--------+-------+-----------+--------+--------+-------+
```


Similar to the suggestion above, I have reduced lr for this to half the initial values and resumed training. Will update here.

**Comment by ArgoHA** [comment]
Thanks @q-prashant, "l" model was the only one I wasn't able to crash, so lr wasn't updated. Let me know which lr will work for you in the end, I will update the default config.

**Comment by q-prashant** [comment]
It still failed but on 13th epoch instead of 11th. Not sure if I should reduce LR further by half. 


![Image](https://github.com/user-attachments/assets/c725004c-38a3-4e01-b51a-9131a68b50ca)

**Comment by ArgoHA** [comment]
@q-prashant what are your current LRs? Base and backbone. 

The issue definitely is in hight LR and it happens after several epochs because of OneCycler. We need to get over the highest point and then training will be stable.

![image](https://github.com/user-attachments/assets/4f9f26c9-c740-4d57-8148-6b270cb93ce0)

**Comment by q-prashant** [comment]
The green one is latest that crashed

![Image](https://github.com/user-attachments/assets/63695967-7d74-45db-8754-fbaaccc7365f)

My lr are:
```console
    l:
      backbone_lr: 0.00000625 #0.0000125
      base_lr: 0.000125 #0.00025
```

**Comment by q-prashant** [comment]
Hey Argo, I will try training with these settings today. 
My batch size is small - I am sharing some settings from config.yaml
```yaml
  use_wandb: True
  device: cuda
  label_to_name: # dataset's classes
    0: ball
  use_one_class: True # Was false 

  img_size: [1024, 1024] # (h, w)
  keep_ratio: False # image aspect ratio, if True - image will be padded
  to_visualize_eval: True # save images with gt and preds
  debug_img_processing: True # save images after preprocessing

  amp_enabled: True # use automatic mixed precision
  clip_max_norm: 0.1 # gradient clipping

  batch_size: 7 # 8 for 1280 | 12 for 1024 #16 # physical, should fit on the device
  b_accum_steps: 1 # grad accumulation (n * bs)
  epochs: 70
  early_stopping: 10 # 0 - no early stopping
  ignore_background_epochs: 0 # background images are not used for N epochs in train set
  num_workers: 12
```
The dataset has 1 class where the object is a ball which is small as compared to the entire image. There is usually a single ball in the image.

**Comment by ArgoHA** [comment]
I am happy that it worked. Thanks for your feedback

**Comment by ArgoHA** [comment]
@Wavelet303 do you have any other questions or updates? If no, I'll close this issue and you'll be able to open a new one when you want

**Comment by Wavelet303** [comment]
Hi @ArgoHA 👋,

Thanks for following up! I’ve conducted multiple experiments (trainings) with different datasets and D-Fine variants, and so far, I haven’t encountered any significant issues. For example, regarding the background image reduction we discussed earlier, I didn’t observe any performance improvement — I think it really depends on the specific characteristics of the dataset and the types of defects.

On the other hand, I believe I may have found a potential bug: when I enable the half precision export option, the script throws an error. This might be worth investigating.

My next step is to implement inference code in C++. Once I have it ready, I’ll be happy to share it with you in case you’d like to integrate it into the repository.

Thanks again for all your hard work on this project — it’s been a great tool so far!

Best,
Wavelet303

**Comment by ArgoHA** [comment]
Hey
```
def wandb_logger(loss, metrics: Dict[str, float], epoch, mode: str) -> None:
    log_data = {"epoch": epoch}
    if loss:
        log_data[f"{mode}/loss/"] = loss

    for metric_name, metric_value in metrics.items():
        log_data[f"{mode}/metrics/{metric_name}"] = metric_value

    wandb.log(log_data)
```

Check the first line - `log_data = {"epoch": epoch}`, epoch is passed actually.

I'll close this issue, please open a new one anytime
